name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file docker/Dockerfile --tag simcax/basicaction:$(date +%s) --platform=linux/arm64 
    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKERUSERNAME }}" -p="${{ secrets.DOCKERPASSWORD }}"
    - name: Docker Push
      run: docker push simcax/basicaction:$(date +%s)
    