name: Docker Image CI

on:
  push:
    branches: [ feature-*, fix-* ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Define tag variables
      run: |
          echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Build image
      run: docker build . --file docker/Dockerfile --tag simcax/basicaction:${{ env.TAG }}
    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKERUSERNAME }}" -p="${{ secrets.DOCKERPASSWORD }}"
    - name: Docker Push
      run: docker push simcax/basicaction:${{ env.TAG }}
    
